import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface ReportData {
  repository: string;
  date: string;
  stats: Array<{
    icon: string;
    label: string;
    value: string | number;
  }>;
  teamMembers: Array<{
    name: string;
    commits: number;
    pullRequests: number;
    issues: number;
    percentage: number;
  }>;
  languages: Array<{
    name: string;
    percentage: number;
  }>;
  commitCount: number;
  pullRequestCount: number;
  latestCommitMessage: string;
}

export const generatePDFReport = async (
  elementId: string,
  reportData: ReportData,
  fileName: string = `github-report-${reportData.repository}-${reportData.date}.pdf`
) => {
  try {
    // Show loading indicator
    const loadingElement = document.createElement('div');
    loadingElement.innerHTML = 'Generating PDF...';
    loadingElement.style.position = 'fixed';
    loadingElement.style.top = '50%';
    loadingElement.style.left = '50%';
    loadingElement.style.transform = 'translate(-50%, -50%)';
    loadingElement.style.backgroundColor = 'rgba(0,0,0,0.8)';
    loadingElement.style.color = 'white';
    loadingElement.style.padding = '20px';
    loadingElement.style.borderRadius = '10px';
    loadingElement.style.zIndex = '9999';
    loadingElement.style.fontSize = '16px';
    document.body.appendChild(loadingElement);

    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error('Element not found');
    }

    // Clone the element to avoid modifying the original
    const cloneElement = element.cloneNode(true) as HTMLElement;
    
    // Style the clone for PDF
    cloneElement.style.width = '800px';
    cloneElement.style.padding = '40px';
    cloneElement.style.backgroundColor = 'white';
    cloneElement.style.position = 'absolute';
    cloneElement.style.left = '-9999px';
    cloneElement.style.top = '0';
    document.body.appendChild(cloneElement);

    // Add report header
    const header = document.createElement('div');
    header.innerHTML = `
      <div style="text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #e1e4e8;">
        <h1 style="color: #24292e; margin-bottom: 10px;">GitHub Repository Report</h1>
        <p style="color: #586069; margin: 5px 0;"><strong>Repository:</strong> ${reportData.repository}</p>
        <p style="color: #586069; margin: 5px 0;"><strong>Generated:</strong> ${reportData.date}</p>
      </div>
    `;
    cloneElement.insertBefore(header, cloneElement.firstChild);

    // Add footer
    const footer = document.createElement('div');
    footer.innerHTML = `
      <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e1e4e8; color: #586069; font-size: 12px;">
        <p>Generated by GitHub Analytics Dashboard</p>
      </div>
    `;
    cloneElement.appendChild(footer);

    // Convert to canvas
    const canvas = await html2canvas(cloneElement, {
      scale: 2,
      backgroundColor: '#ffffff',
      logging: false,
      useCORS: true,
    });

    // Remove the clone
    document.body.removeChild(cloneElement);

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    pdf.save(fileName);

    // Remove loading indicator
    document.body.removeChild(loadingElement);
    
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};